name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      # Step 4: Build the frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Step 5: Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
	  personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./frontend/build
          # Optionally set the branch you want to deploy to
          publish_branch: gh-pages
